<?php

function anchor($key){
    $base = basename(__FILE__, '.phtml');
    $base = "$base-$key";
    return $base;
}

$news = [
    [
        'title' => 'New ACA Rating Methodology Effective January 1',
        'body'  => '
            <br>
            <div>
            As of January 1, 2018 the ACA age band structure will be adjusted to expand the number of single age bands
            <span> for dependent children</span> in the 0-20 age segment.&nbsp; Additionally, the definition of the 3:1 ratio rule has been adjusted.&nbsp;
            </div>&nbsp;&nbsp;
            <br> Missed our blog post?
            <a style="color:rgb(92, 56, 129);font-weight:bold;text-decoration:underline;" rel="nofollow" track="on" shape="rect" href="https://benefitsdoneright.com/blog.php?post=170811&amp;utm_source=November+Newsletter+2017%2F10%2F30%2C+1%3A30+PM&amp;utm_campaign=April+2016+Group+Newsletter&amp;utm_medium=email" linktype="1" target="_blank">Read it here.</a>
        ',
    ],
    [
        'title' => 'HR Done Right Blog: Employee Retention Strategies in a Competitive Job Market',
        'body'  => '
            <br>
            <span>
            <div>
            <div>
            According to the Bureau of Labor Statistics, the national unemployment rate dropped to 4.1 percent in October. Job gains occurred in food services and drinking establishments, professional and business services, manufacturing and health care. When the unemployment rate is low, employers often find themselves competing to retain and attract talent.
            <br>
            <br>
            </div>
            </div> </span>Click here to read the&nbsp;
            <span style="color:#003d72;"><strong><a style="color:rgb(92, 56, 129);font-weight:bold;text-decoration:underline;" rel="nofollow" track="on" shape="rect" href="https://hrdoneright.com/blog.php?post=28&amp;utm_source=November+Newsletter+2017%2F10%2F30%2C+1%3A30+PM&amp;utm_campaign=April+2016+Group+Newsletter&amp;utm_medium=email" linktype="1" target="_blank">HR Done Right</a></strong></span> blog.
        ',
    ],
    [
        'title' => '2018 FSA & 401(k) Limits Announced ',
        'body'  => '
            <div style="text-align:left;" align="left">
                The IRS has announced that the contribution limits for health flexible spending arrangements (health FSAs) and 401(k) retirement plans will increase in 2018 as follows:
            </div>
            <div style="text-align:left;" align="left">
                <ul>
                <li>Health FSAs: The annual dollar limit on employee contributions to employer-sponsored health FSAs will be $2,650 (up from $2,600 for 2017).</li>
                <li>401(k) Plans: The contribution limit for employees who participate in 401(k) plans will be $18,500 (up from $18,000 for 2017). The catch-up contribution limit for those aged 50 and over will remain unchanged at $6,000.</li>
                </ul>
            </div>
            <div style="text-align:left;" align="left">
                For more information on these and other new tax benefit limits, please see
                <a style="color:rgb(92, 56, 129);font-weight:bold;text-decoration:underline;" rel="nofollow" track="on" shape="rect" href="https://www.irs.gov/pub/irs-drop/rp-17-58.pdf?utm_source=November+Newsletter+2017%2F10%2F30%2C+1%3A30+PM&amp;utm_campaign=April+2016+Group+Newsletter&amp;utm_medium=email" linktype="1" target="_blank">IRS Revenue Procedure 2017-58</a> and
                <a style="color:rgb(92, 56, 129);font-weight:bold;text-decoration:underline;" rel="nofollow" track="on" shape="rect" href="https://www.irs.gov/pub/irs-drop/n-17-64.pdf?utm_source=November+Newsletter+2017%2F10%2F30%2C+1%3A30+PM&amp;utm_campaign=April+2016+Group+Newsletter&amp;utm_medium=email" linktype="1" target="_blank">IRS Notice 2017-64</a>.
                <br>
                <br>
            </div>
            <div style="text-align:left;" align="left">
                <div style="font-size:8pt;">
                <em><br></em>
                </div>
                <div style="font-size:8pt;">
                <em>Article reprinted with permission from HR360.com</em>
                <br>
                </div>
            </div>
        ',
    ],
    [
        'title' => 'Coming Soon: ACA Employer Penalty Assessments',
        'body'  => '
            <div>
                <div>
                On November 2, the Internal Revenue Service (IRS) issued revised FAQs on the employer shared responsibility provisions under the Affordable Care Act (ACA). Question sets 55-58 now detail the procedure the IRS will use to begin issuing proposed penalty assessments to employers that failed to comply with these provisions in 2015. Though the IRS was previously silent on the details of penalty assessments, this new information serves as a reminder to employers that compliance enforcement is a priority for the IRS.&nbsp; &nbsp;
                </div>
                <br>
            </div>
            <div>
                <a style="color:rgb(92, 56, 129);font-weight:bold;text-decoration:underline;" rel="nofollow" track="on" shape="rect" href="http://bit.ly/2zGTB7o?utm_source=November+Newsletter+2017%2F10%2F30%2C+1%3A30+PM&amp;utm_campaign=April+2016+Group+Newsletter&amp;utm_medium=email" linktype="1" target="_blank">Click here</a> to read the full article.
            </div>
        ',
    ],
    [
        'title' => 'Office Closure: Thanksgiving Holiday',
        'body'  =>'
            <div>
                <br>
                <div>
                Benefits Done Right will be closed Thursday, November 23, 2017 and Friday, November 24, 2017 in observance of the Thanksgiving holiday.
                </div>
                <br>
                <div>
                We will process and respond to all email, faxes and voicemails promptly when normal business hours resume at 7:30 AM on Monday, November 27, 2017.&nbsp;
                </div>
                <br>
            </div>
            '
    ],
];
?>

<div class="OuterBGColor" style="background-image:none;background-repeat:repeat;background-color:#fff"  id="rootDiv" align="center">
    <table class="OuterBGColor" style="margin-right:auto;margin-left:auto;background-image:none;background-repeat:repeat;"  border="0" width="100%" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td class="HideInMobile" rowspan="1" colspan="1"><img height="5" vspace="0" border="0" hspace="0" width="1" alt="" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                </td>
                <td class="MainWidth" style="width:100%;" valign="top" rowspan="1" colspan="1" align="center">
                    <div class="MaxMainWidth" style="margin-left:auto;max-width:100%;margin-right:auto;" align="center">
                        <table border="0" width="100%" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td class="BodyPadding" style="padding:15px 5px 15px 5px;" valign="top" rowspan="1" colspan="1" align="center">
                                        <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td class="TopMargin" style="padding:0px 0px 8px 0px;" valign="top" width="100%" rowspan="1" colspan="1" align="center"> </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <table class="BorderColor" style="background-color:#585858;" bgcolor="#585858" border="0" width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td class="BorderWidth" style="padding:1px 1px 1px 1px;" valign="top" width="100%" rowspan="1" colspan="1" align="center">
                                                        <table class="InnerBGColor" style="background-color:#FFFFFF;" bgcolor="#FFFFFF" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                            <tbody>
                                                                <tr>
                                                                    <td class="EmailContainer" style="padding:0px 0px 15px 0px;" valign="top" width="100%" rowspan="1" colspan="1" align="center">
                                                                        <table class="CC_Divider" style="margin:0px auto 0px auto;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="DividerPadding" style="padding:15px 20px 15px 20px;line-height:1px;height:1px;" valign="top" width="100%" rowspan="1" colspan="1" align="center">
                                                                                        <table style="height:1px;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td class="DividerHeight DividerBGColor" style="background-color:#585858;padding-bottom:0px;line-height:1px;height:1px;" height="1" bgcolor="#585858" rowspan="1" colspan="1" align="center"><img height="1" vspace="0" border="0" hspace="0" width="5" style="display: block; height:1px; width:5px;" alt="" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <table style="background-color:#ffffff;" bgcolor="#FFFFFF" border="0" width="100%" cellpadding="0" cellspacing="0" id="content_LETTER.BLOCK29">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="SubheadlineContent SubheadlineText" style="padding:8px 20px 9px 20px;color:#585858;font-weight:bold;font-size:14pt;font-family:Trebuchet MS,Verdana,Helvetica,sans-serif;text-align:right;" valign="top" rowspan="1" colspan="1" align="right">&nbsp; &nbsp;&nbsp;
                                                                                        <table class="OneColumnMobile" style="margin-right:5px;" width="193" data-padding-converted="true" cellpadding="0" cellspacing="0" align="left">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td style="padding:0px;" width="100%" rowspan="1" colspan="1">
                                                                                                        <div align="center">
                                                                                                            <a class="imgCaptionAnchor" rel="nofollow" track="on" href="http://www.hrdoneright.com" shape="rect" target="_blank"><img class="cc-image-resize" height="58" vspace="0" name="ACCOUNT.IMAGE.1" border="0" hspace="0" width="193" src="https://files.constantcontact.com/23a38148601/a27fc860-1854-4f17-8162-12c8fa9a536c.jpg?a=1128927022308"></a>
                                                                                                        </div>
                                                                                                    </td>
                                                                                                    <td class="SpacerImageContainer mobile-hidden" style="line-height:1px;height:1px;padding-right:5px;" height="1" valign="top" width="5" rowspan="1" colspan="1" align="center"><img height="1" vspace="0" border="0" hspace="0" width="5" class="SpacerImage" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                        <div style="color:#3d3d3d;">
                                                                                            November 2017
                                                                                        </div>
                                                                                        <div style="color:#003d72;text-align:right;" align="right">
                                                                                            Stay Current Newsletter
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <table style="background-color:#ffffff;" bgcolor="#FFFFFF" border="0" width="100%" cellpadding="0" cellspacing="0" id="content_LETTER.BLOCK31">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="Content MainText" style="padding:8px 20px 9px 20px;color:#333333;font-size:10pt;font-family:Verdana,Geneva,Arial,Helvetica,sans-serif;" valign="top" rowspan="1" colspan="1" align="left">
                                                                                        <div style="text-align:left;" align="left">
                                                                                            <span><span style="font-family:'Trebuchet MS',' Verdana',' Helvetica',' sans-serif';">&nbsp;</span><strong>In This Issue:<a shape="rect" name="Top"><img alt="Top" title="Top" src="https://imgssl.constantcontact.com/ui/images1/s.gif"></a></strong>
                                                                                            </span>
                                                                                        </div>
                                                                                        <div style="color:#585858;font-size:10pt;font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;text-align:left;" align="left">
                                                                                            <ul>
                                                                                                <?php foreach ($news as $key => $item) :?>

                                                                                                <li style="color:#585858;font-size:10pt;font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;">
                                                                                                    <b>
                                                                                                        <a style="color:rgb(88, 88, 88);font-weight:bold;text-decoration:none;" shape="rect" linktype="anchor"
                                                                                                            href="#news<?=anchor($key)?>"
                                                                                                        >
                                                                                                            <?=$item['title']?>
                                                                                                        </a>
                                                                                                    </b>
                                                                                                </li>
                                                                                                <?php endforeach ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <table class="CC_Divider" style="margin:0px auto 0px auto;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="DividerPadding" style="padding:15px 20px 15px 20px;line-height:1px;height:1px;" valign="top" width="100%" rowspan="1" colspan="1" align="center">
                                                                                        <table style="height:1px;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td class="DividerHeight DividerBGColor" style="background-color:#585858;padding-bottom:0px;line-height:1px;height:1px;" height="1" bgcolor="#585858" rowspan="1" colspan="1" align="center"><img height="1" vspace="0" border="0" hspace="0" width="5" style="display: block; height:1px; width:5px;" alt="" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>

                                                                        <?php foreach ($news as $key => $item) :?>
                                                                        <table border="0" width="100%" cellpadding="0" cellspacing="0" id="news<?=anchor($key)?>">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="ArticlePadding MainText" style="padding:8px 20px 9px 20px;color:#333333;font-size:10pt;font-family:Verdana,Geneva,Arial,Helvetica,sans-serif;" valign="top" rowspan="1" colspan="1" align="left">
                                                                                        <div class="ArticleHeadlineText" style="color:#585858;font-weight:bold;font-size:14pt;font-family:Trebuchet MS,Verdana,Helvetica,sans-serif;">
                                                                                            <a shape="rect" name="art1"><img alt="art1" src="https://imgssl.constantcontact.com/ui/images1/s.gif" title="art1"></a>
                                                                                            <?=$item['title']?>
                                                                                            <br>
                                                                                        </div>
                                                                                        <div class="ArticleHeadlineText" style="color:#585858;font-weight:bold;font-size:14pt;font-family:Trebuchet MS,Verdana,Helvetica,sans-serif;">
                                                                                            <br>
                                                                                        </div>
                                                                                        <?=$item['body']?>

                                                                                        <div style="text-align:right;" align="right">
                                                                                            <span style="color:#003d72;font-size:8pt;"><strong><em><a style="color:rgb(0, 61, 114);font-weight:bold;text-decoration:none;font-style:italic;" href="#Top" shape="rect" linktype="anchor">Back to Top</a> </em></strong></span>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <table class="CC_Divider" style="margin:0px auto 0px auto;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="DividerPadding" style="padding:15px 20px 15px 20px;line-height:1px;height:1px;" valign="top" width="100%" rowspan="1" colspan="1" align="center">
                                                                                        <table style="height:1px;" border="0" width="100%" cellspacing="0" cellpadding="0">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td class="DividerHeight DividerBGColor" style="background-color:#585858;padding-bottom:0px;line-height:1px;height:1px;" height="1" bgcolor="#585858" rowspan="1" colspan="1" align="center"><img height="1" vspace="0" border="0" hspace="0" width="5" style="display: block; height:1px; width:5px;" alt="" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <?php endforeach ?>



                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td class="BottomMargin" style="padding:9px 0px 8px 0px;" valign="top" width="100%" rowspan="1" colspan="1" align="center"> </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
                <td class="HideInMobile" rowspan="1" colspan="1"><img height="5" vspace="0" border="0" hspace="0" width="1" alt="" src="https://imgssl.constantcontact.com/letters/images/sys/S.gif">
                </td>
            </tr>
        </tbody>
    </table>
</div>
